name: publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: publish site
      env:
        USER: ${{ secrets.USER }}
        TOKEN: ${{ secrets.TOKEN }}
      run: |
          curl --fail --user "$USER:$TOKEN" --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds

